
package graficoarraylist;

import java.util.ArrayList;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/*La clase DefaultTableModel es una subclase del AbstractTableModel. 
Como su nombre lo indica, es el modelo de tabla que utiliza una JTable 
cuando el programador no define específicamente ningún modelo de tabla.  
El DefaultTableModel almacena los datos de la JTable en una estructura "array de arrays".
*/

/**
 *
 * @author davidmramirez
 */
public class Vista extends javax.swing.JFrame {

    //definir variables para "eliminar"
    String nombre = "";
    String apellido = "";
    String cedula = "";
    String telefono = "";
    
   
    ArrayList<Alumno> lista = new ArrayList<>();

       
    public Vista() {
        initComponents();
        
        //este bloque de código es para agregar el mouse listener al Jtable e implementar la clase DefaultTableModel    
        
        jTableAlumno.addMouseListener(new MouseAdapter(){
        DefaultTableModel model = new DefaultTableModel();
        //DefaultTableModel model = (DefaultTableModel) jTableAlumno.getModel();
       
        public void mouseClicked(MouseEvent e){
        int i = jTableAlumno.getSelectedRow();
        nombre = (jTableAlumno.getValueAt(i, 0).toString());
        apellido = (jTableAlumno.getValueAt(i, 1).toString());
        cedula = (jTableAlumno.getValueAt(i, 2).toString());
        telefono = (jTableAlumno.getValueAt(i, 3).toString());
        }});
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        BtnRegistrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAlumno = new javax.swing.JTable();
        BtnEliminar = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        BtnGuardaModificacion = new javax.swing.JButton();
        BtnGeneraTxt = new javax.swing.JButton();
        BtnImportaTxt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setText("Agregar datos de alumno");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido");

        jLabel4.setText("Cédula");

        jLabel5.setText("Télefono");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });

        BtnRegistrar.setText("Registrar");
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });

        jTableAlumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Cédula", "Teléfono"
            }
        ));
        jScrollPane1.setViewportView(jTableAlumno);

        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        BtnModificar.setText("Modificar");
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });

        BtnGuardaModificacion.setText("Guardar Modificación");
        BtnGuardaModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardaModificacionActionPerformed(evt);
            }
        });

        BtnGeneraTxt.setText("Exportar .txt");
        BtnGeneraTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGeneraTxtActionPerformed(evt);
            }
        });

        BtnImportaTxt.setText("Importar .txt");
        BtnImportaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnImportaTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(txtNombre)
                                    .addComponent(txtApellido)
                                    .addComponent(txtCedula)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BtnRegistrar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BtnEliminar)
                                        .addGap(12, 12, 12)
                                        .addComponent(BtnModificar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BtnGuardaModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BtnGeneraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(BtnImportaTxt)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnRegistrar)
                            .addComponent(BtnEliminar)
                            .addComponent(BtnModificar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnGuardaModificacion)
                            .addComponent(BtnGeneraTxt)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnImportaTxt)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //función para imprimir los datos de los textFields en la tabla:
    public void mostrar()
    {
        //creamos una matriz de tipo string, inicializamos con los tamaños del ArrayList.
        String matriz[][]=new String[lista.size()][4];
        
        //for para recorrer el tamaño de la lista que tenga.
        for(int i = 0; i < lista.size(); i++)
        {
            //getters y setters que he creado en el objeto Alumno
            matriz[i][0]=lista.get(i).getNombre();
            matriz[i][1]=lista.get(i).getApellido();
            matriz[i][2]=lista.get(i).getCedula();
            matriz[i][3]=lista.get(i).getTelefono();
        }
    
    jTableAlumno.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
            new String [] {
                "Nombre", "Apellido", "Cédula", "Teléfono"
            }
        ));
    
    }
    
    
    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed


    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed

        //inicializamos el objeto y en el constructor, las 4 variables con las funciones
        //para traer los datos de los textfields.
        Alumno alumno = new Alumno(txtNombre.getText(),txtApellido.getText(),txtCedula.getText(),txtTelefono.getText());
        //añado el registro a mi lista por medio del método add
        lista.add(alumno);
        //llamo a función para imprimir los datos de los textFields en la tabla:
        mostrar();
        //funciones para borrar textos residuales en textFields
        txtNombre.setText("");
        txtApellido.setText("");
        txtCedula.setText("");
        txtTelefono.setText("");
        
    }//GEN-LAST:event_BtnRegistrarActionPerformed


    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        // For para recorrer todo el tamaño de la lista
        for (int i = 0; i < lista.size(); i++){
        //condicional para obtener el elemento y removerlo. Usamos equals para no usar un ==
        if(nombre.equals(lista.get(i).getNombre())){
        lista.remove(i);
        }
        }
        //invoco función mostrar() para actualizar la tabla:
        mostrar();
        
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        // al hacer clic, imprime en los campos de texto los valores de cada campo con el método setText():
        txtNombre.setText(nombre);
        txtApellido.setText(apellido);
        txtCedula.setText(cedula);
        txtTelefono.setText(telefono);
        
    }//GEN-LAST:event_BtnModificarActionPerformed

    private void BtnGuardaModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardaModificacionActionPerformed
     
          for (int i = 0; i < lista.size(); i++) {
            if(cedula.equals(lista.get(i).getCedula())){
            lista.get(i).setNombre(txtNombre.getText());
            lista.get(i).setApellido(txtApellido.getText());
            lista.get(i).setCedula(txtCedula.getText());
            lista.get(i).setTelefono(txtTelefono.getText());
            }
        }
        
        txtNombre.setText("");
        txtApellido.setText("");
        txtCedula.setText("");
        txtTelefono.setText("");
        
        mostrar();
   
    }//GEN-LAST:event_BtnGuardaModificacionActionPerformed


    private void BtnGeneraTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGeneraTxtActionPerformed
        
               
try{
        FileWriter pw = new FileWriter("archivocreado.txt"); //nombre del archivo
        
    // Bucle For para recorrer la lista:
        for (int i = 0; i < lista.size(); i++) {

                pw.write(lista.get(i).getNombre()+",");
                pw.write(lista.get(i).getApellido()+",");
                pw.write(lista.get(i).getCedula()+","); 
                pw.write(lista.get(i).getTelefono()+"\n");
      
        }                                                     
        pw.close();
        JOptionPane.showMessageDialog(null, "Archivo Creado");
        }catch(Exception err){
            System.out.println(err);    
            } 
    
    mostrar();
        
    }//GEN-LAST:event_BtnGeneraTxtActionPerformed

    private void BtnImportaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnImportaTxtActionPerformed
     
       //Nombre y ruta del archivo a importar
       String filePath ="archivocreado5.txt";
       File file = new File(filePath); 

       try{
           BufferedReader buffer = new BufferedReader (new FileReader(file));
       
           Object[] filasTxt = buffer.lines().toArray();
           //System.out.println("cant de registros: " + filasTxt.length);
       
           String matriz[][]=new String[filasTxt.length][4];
           
           //for para hacer el split y recorrer el la matriz del jTableAlumno según la cant. de filas del .txt  
           for (int x = 0; x < filasTxt.length; x++){
       
           String fila = filasTxt[x].toString().trim();
           String[] campo = fila.split(",");
                     
           matriz[x][0]= campo[0];                      
           matriz[x][1]= campo[1];                      
           matriz[x][2]= campo[2];                   
           matriz[x][3]= campo[3];
                     
           }
        
        jTableAlumno.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
            new String [] {
                "Nombre", "Apellido", "Cédula", "Teléfono"
            }
        ));        

       }catch (Exception err){
       System.out.println(err);  
       }

    }//GEN-LAST:event_BtnImportaTxtActionPerformed

 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnGeneraTxt;
    private javax.swing.JButton BtnGuardaModificacion;
    private javax.swing.JButton BtnImportaTxt;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAlumno;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
